# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desiger/ui_periodic_table.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 583)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ba = QtWidgets.QPushButton(self.centralwidget)
        self.ba.setMinimumSize(QtCore.QSize(52, 52))
        self.ba.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ba.setFont(font)
        self.ba.setObjectName("ba")
        self.gridLayout.addWidget(self.ba, 5, 1, 1, 1)
        self.ti = QtWidgets.QPushButton(self.centralwidget)
        self.ti.setMinimumSize(QtCore.QSize(52, 52))
        self.ti.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ti.setFont(font)
        self.ti.setObjectName("ti")
        self.gridLayout.addWidget(self.ti, 3, 3, 1, 1)
        self.si = QtWidgets.QPushButton(self.centralwidget)
        self.si.setMinimumSize(QtCore.QSize(52, 52))
        self.si.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.si.setFont(font)
        self.si.setObjectName("si")
        self.gridLayout.addWidget(self.si, 2, 13, 1, 1)
        self.k = QtWidgets.QPushButton(self.centralwidget)
        self.k.setMinimumSize(QtCore.QSize(52, 52))
        self.k.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.k.setFont(font)
        self.k.setObjectName("k")
        self.gridLayout.addWidget(self.k, 3, 0, 1, 1)
        self.p = QtWidgets.QPushButton(self.centralwidget)
        self.p.setMinimumSize(QtCore.QSize(52, 52))
        self.p.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.p.setFont(font)
        self.p.setObjectName("p")
        self.gridLayout.addWidget(self.p, 2, 14, 1, 1)
        self.b = QtWidgets.QPushButton(self.centralwidget)
        self.b.setMinimumSize(QtCore.QSize(52, 52))
        self.b.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.b.setFont(font)
        self.b.setObjectName("b")
        self.gridLayout.addWidget(self.b, 1, 12, 1, 1)
        self.cl = QtWidgets.QPushButton(self.centralwidget)
        self.cl.setMinimumSize(QtCore.QSize(52, 52))
        self.cl.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cl.setFont(font)
        self.cl.setObjectName("cl")
        self.gridLayout.addWidget(self.cl, 2, 16, 1, 1)
        self.al = QtWidgets.QPushButton(self.centralwidget)
        self.al.setMinimumSize(QtCore.QSize(52, 52))
        self.al.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.al.setFont(font)
        self.al.setObjectName("al")
        self.gridLayout.addWidget(self.al, 2, 12, 1, 1)
        self.sc = QtWidgets.QPushButton(self.centralwidget)
        self.sc.setMinimumSize(QtCore.QSize(52, 52))
        self.sc.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sc.setFont(font)
        self.sc.setObjectName("sc")
        self.gridLayout.addWidget(self.sc, 3, 2, 1, 1)
        self.ne = QtWidgets.QPushButton(self.centralwidget)
        self.ne.setMinimumSize(QtCore.QSize(52, 52))
        self.ne.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ne.setFont(font)
        self.ne.setObjectName("ne")
        self.gridLayout.addWidget(self.ne, 1, 17, 1, 1)
        self.ca = QtWidgets.QPushButton(self.centralwidget)
        self.ca.setMinimumSize(QtCore.QSize(52, 52))
        self.ca.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ca.setFont(font)
        self.ca.setObjectName("ca")
        self.gridLayout.addWidget(self.ca, 3, 1, 1, 1)
        self.ni = QtWidgets.QPushButton(self.centralwidget)
        self.ni.setMinimumSize(QtCore.QSize(52, 52))
        self.ni.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ni.setFont(font)
        self.ni.setObjectName("ni")
        self.gridLayout.addWidget(self.ni, 3, 9, 1, 1)
        self.s = QtWidgets.QPushButton(self.centralwidget)
        self.s.setMinimumSize(QtCore.QSize(52, 52))
        self.s.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.s.setFont(font)
        self.s.setObjectName("s")
        self.gridLayout.addWidget(self.s, 2, 15, 1, 1)
        self.mg = QtWidgets.QPushButton(self.centralwidget)
        self.mg.setMinimumSize(QtCore.QSize(52, 52))
        self.mg.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.mg.setFont(font)
        self.mg.setObjectName("mg")
        self.gridLayout.addWidget(self.mg, 2, 1, 1, 1)
        self.i = QtWidgets.QPushButton(self.centralwidget)
        self.i.setMinimumSize(QtCore.QSize(52, 52))
        self.i.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.i.setFont(font)
        self.i.setObjectName("i")
        self.gridLayout.addWidget(self.i, 4, 16, 1, 1)
        self.be = QtWidgets.QPushButton(self.centralwidget)
        self.be.setMinimumSize(QtCore.QSize(52, 52))
        self.be.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.be.setFont(font)
        self.be.setObjectName("be")
        self.gridLayout.addWidget(self.be, 1, 1, 1, 1)
        self.kr = QtWidgets.QPushButton(self.centralwidget)
        self.kr.setMinimumSize(QtCore.QSize(52, 52))
        self.kr.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.kr.setFont(font)
        self.kr.setObjectName("kr")
        self.gridLayout.addWidget(self.kr, 3, 17, 1, 1)
        self.fe = QtWidgets.QPushButton(self.centralwidget)
        self.fe.setMinimumSize(QtCore.QSize(52, 52))
        self.fe.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.fe.setFont(font)
        self.fe.setObjectName("fe")
        self.gridLayout.addWidget(self.fe, 3, 7, 1, 1)
        self.br = QtWidgets.QPushButton(self.centralwidget)
        self.br.setMinimumSize(QtCore.QSize(52, 52))
        self.br.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.br.setFont(font)
        self.br.setObjectName("br")
        self.gridLayout.addWidget(self.br, 3, 16, 1, 1)
        self.h = QtWidgets.QPushButton(self.centralwidget)
        self.h.setMinimumSize(QtCore.QSize(52, 52))
        self.h.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.h.setFont(font)
        self.h.setObjectName("h")
        self.gridLayout.addWidget(self.h, 0, 0, 1, 1)
        self.co = QtWidgets.QPushButton(self.centralwidget)
        self.co.setMinimumSize(QtCore.QSize(52, 52))
        self.co.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.co.setFont(font)
        self.co.setObjectName("co")
        self.gridLayout.addWidget(self.co, 3, 8, 1, 1)
        self.ge = QtWidgets.QPushButton(self.centralwidget)
        self.ge.setMinimumSize(QtCore.QSize(52, 52))
        self.ge.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ge.setFont(font)
        self.ge.setObjectName("ge")
        self.gridLayout.addWidget(self.ge, 3, 13, 1, 1)
        self.zn = QtWidgets.QPushButton(self.centralwidget)
        self.zn.setMinimumSize(QtCore.QSize(52, 52))
        self.zn.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.zn.setFont(font)
        self.zn.setObjectName("zn")
        self.gridLayout.addWidget(self.zn, 3, 11, 1, 1)
        self.v = QtWidgets.QPushButton(self.centralwidget)
        self.v.setMinimumSize(QtCore.QSize(52, 52))
        self.v.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.v.setFont(font)
        self.v.setObjectName("v")
        self.gridLayout.addWidget(self.v, 3, 4, 1, 1)
        self.na = QtWidgets.QPushButton(self.centralwidget)
        self.na.setMinimumSize(QtCore.QSize(52, 52))
        self.na.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.na.setFont(font)
        self.na.setObjectName("na")
        self.gridLayout.addWidget(self.na, 2, 0, 1, 1)
        self.cr = QtWidgets.QPushButton(self.centralwidget)
        self.cr.setMinimumSize(QtCore.QSize(52, 52))
        self.cr.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cr.setFont(font)
        self.cr.setObjectName("cr")
        self.gridLayout.addWidget(self.cr, 3, 5, 1, 1)
        self.mn = QtWidgets.QPushButton(self.centralwidget)
        self.mn.setMinimumSize(QtCore.QSize(52, 52))
        self.mn.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.mn.setFont(font)
        self.mn.setObjectName("mn")
        self.gridLayout.addWidget(self.mn, 3, 6, 1, 1)
        self.ar = QtWidgets.QPushButton(self.centralwidget)
        self.ar.setMinimumSize(QtCore.QSize(52, 52))
        self.ar.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ar.setFont(font)
        self.ar.setObjectName("ar")
        self.gridLayout.addWidget(self.ar, 2, 17, 1, 1)
        self.ga = QtWidgets.QPushButton(self.centralwidget)
        self.ga.setMinimumSize(QtCore.QSize(52, 52))
        self.ga.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ga.setFont(font)
        self.ga.setObjectName("ga")
        self.gridLayout.addWidget(self.ga, 3, 12, 1, 1)
        self.li = QtWidgets.QPushButton(self.centralwidget)
        self.li.setMinimumSize(QtCore.QSize(52, 52))
        self.li.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.li.setFont(font)
        self.li.setObjectName("li")
        self.gridLayout.addWidget(self.li, 1, 0, 1, 1)
        self.he = QtWidgets.QPushButton(self.centralwidget)
        self.he.setMinimumSize(QtCore.QSize(52, 52))
        self.he.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.he.setFont(font)
        self.he.setObjectName("he")
        self.gridLayout.addWidget(self.he, 0, 17, 1, 1)
        self.cu = QtWidgets.QPushButton(self.centralwidget)
        self.cu.setMinimumSize(QtCore.QSize(52, 52))
        self.cu.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cu.setFont(font)
        self.cu.setObjectName("cu")
        self.gridLayout.addWidget(self.cu, 3, 10, 1, 1)
        self.c = QtWidgets.QPushButton(self.centralwidget)
        self.c.setMinimumSize(QtCore.QSize(52, 52))
        self.c.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.c.setFont(font)
        self.c.setObjectName("c")
        self.gridLayout.addWidget(self.c, 1, 13, 1, 1)
        self.o = QtWidgets.QPushButton(self.centralwidget)
        self.o.setMinimumSize(QtCore.QSize(52, 52))
        self.o.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.o.setFont(font)
        self.o.setObjectName("o")
        self.gridLayout.addWidget(self.o, 1, 15, 1, 1)
        self.f = QtWidgets.QPushButton(self.centralwidget)
        self.f.setMinimumSize(QtCore.QSize(52, 52))
        self.f.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.f.setFont(font)
        self.f.setObjectName("f")
        self.gridLayout.addWidget(self.f, 1, 16, 1, 1)
        self.hf = QtWidgets.QPushButton(self.centralwidget)
        self.hf.setMinimumSize(QtCore.QSize(52, 52))
        self.hf.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hf.setFont(font)
        self.hf.setObjectName("hf")
        self.gridLayout.addWidget(self.hf, 5, 3, 1, 1)
        self.lu = QtWidgets.QPushButton(self.centralwidget)
        self.lu.setMinimumSize(QtCore.QSize(52, 52))
        self.lu.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lu.setFont(font)
        self.lu.setObjectName("lu")
        self.gridLayout.addWidget(self.lu, 5, 2, 1, 1)
        self.nb = QtWidgets.QPushButton(self.centralwidget)
        self.nb.setMinimumSize(QtCore.QSize(52, 52))
        self.nb.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.nb.setFont(font)
        self.nb.setObjectName("nb")
        self.gridLayout.addWidget(self.nb, 4, 4, 1, 1)
        self.se = QtWidgets.QPushButton(self.centralwidget)
        self.se.setMinimumSize(QtCore.QSize(52, 52))
        self.se.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.se.setFont(font)
        self.se.setObjectName("se")
        self.gridLayout.addWidget(self.se, 3, 15, 1, 1)
        self.arsenic = QtWidgets.QPushButton(self.centralwidget)
        self.arsenic.setMinimumSize(QtCore.QSize(52, 52))
        self.arsenic.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.arsenic.setFont(font)
        self.arsenic.setObjectName("arsenic")
        self.gridLayout.addWidget(self.arsenic, 3, 14, 1, 1)
        self.ag = QtWidgets.QPushButton(self.centralwidget)
        self.ag.setMinimumSize(QtCore.QSize(52, 52))
        self.ag.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ag.setFont(font)
        self.ag.setObjectName("ag")
        self.gridLayout.addWidget(self.ag, 4, 10, 1, 1)
        self.sr = QtWidgets.QPushButton(self.centralwidget)
        self.sr.setMinimumSize(QtCore.QSize(52, 52))
        self.sr.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sr.setFont(font)
        self.sr.setObjectName("sr")
        self.gridLayout.addWidget(self.sr, 4, 1, 1, 1)
        self.zr = QtWidgets.QPushButton(self.centralwidget)
        self.zr.setMinimumSize(QtCore.QSize(52, 52))
        self.zr.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.zr.setFont(font)
        self.zr.setObjectName("zr")
        self.gridLayout.addWidget(self.zr, 4, 3, 1, 1)
        self.rb = QtWidgets.QPushButton(self.centralwidget)
        self.rb.setMinimumSize(QtCore.QSize(52, 52))
        self.rb.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rb.setFont(font)
        self.rb.setObjectName("rb")
        self.gridLayout.addWidget(self.rb, 4, 0, 1, 1)
        self.og = QtWidgets.QPushButton(self.centralwidget)
        self.og.setMinimumSize(QtCore.QSize(52, 52))
        self.og.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.og.setFont(font)
        self.og.setObjectName("og")
        self.gridLayout.addWidget(self.og, 6, 17, 1, 1)
        self.ts = QtWidgets.QPushButton(self.centralwidget)
        self.ts.setMinimumSize(QtCore.QSize(52, 52))
        self.ts.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ts.setFont(font)
        self.ts.setObjectName("ts")
        self.gridLayout.addWidget(self.ts, 6, 16, 1, 1)
        self.lv = QtWidgets.QPushButton(self.centralwidget)
        self.lv.setMinimumSize(QtCore.QSize(52, 52))
        self.lv.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lv.setFont(font)
        self.lv.setObjectName("lv")
        self.gridLayout.addWidget(self.lv, 6, 15, 1, 1)
        self.mc = QtWidgets.QPushButton(self.centralwidget)
        self.mc.setMinimumSize(QtCore.QSize(52, 52))
        self.mc.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.mc.setFont(font)
        self.mc.setObjectName("mc")
        self.gridLayout.addWidget(self.mc, 6, 14, 1, 1)
        self.cd = QtWidgets.QPushButton(self.centralwidget)
        self.cd.setMinimumSize(QtCore.QSize(52, 52))
        self.cd.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cd.setFont(font)
        self.cd.setObjectName("cd")
        self.gridLayout.addWidget(self.cd, 4, 11, 1, 1)
        self.fl = QtWidgets.QPushButton(self.centralwidget)
        self.fl.setMinimumSize(QtCore.QSize(52, 52))
        self.fl.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.fl.setFont(font)
        self.fl.setObjectName("fl")
        self.gridLayout.addWidget(self.fl, 6, 13, 1, 1)
        self.nh = QtWidgets.QPushButton(self.centralwidget)
        self.nh.setMinimumSize(QtCore.QSize(52, 52))
        self.nh.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.nh.setFont(font)
        self.nh.setObjectName("nh")
        self.gridLayout.addWidget(self.nh, 6, 12, 1, 1)
        self.cs = QtWidgets.QPushButton(self.centralwidget)
        self.cs.setMinimumSize(QtCore.QSize(52, 52))
        self.cs.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cs.setFont(font)
        self.cs.setObjectName("cs")
        self.gridLayout.addWidget(self.cs, 5, 0, 1, 1)
        self.cn = QtWidgets.QPushButton(self.centralwidget)
        self.cn.setMinimumSize(QtCore.QSize(52, 52))
        self.cn.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cn.setFont(font)
        self.cn.setObjectName("cn")
        self.gridLayout.addWidget(self.cn, 6, 11, 1, 1)
        self.rg = QtWidgets.QPushButton(self.centralwidget)
        self.rg.setMinimumSize(QtCore.QSize(52, 52))
        self.rg.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rg.setFont(font)
        self.rg.setObjectName("rg")
        self.gridLayout.addWidget(self.rg, 6, 10, 1, 1)
        self.ru = QtWidgets.QPushButton(self.centralwidget)
        self.ru.setMinimumSize(QtCore.QSize(52, 52))
        self.ru.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ru.setFont(font)
        self.ru.setObjectName("ru")
        self.gridLayout.addWidget(self.ru, 4, 7, 1, 1)
        self.ds = QtWidgets.QPushButton(self.centralwidget)
        self.ds.setMinimumSize(QtCore.QSize(52, 52))
        self.ds.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ds.setFont(font)
        self.ds.setObjectName("ds")
        self.gridLayout.addWidget(self.ds, 6, 9, 1, 1)
        self.mt = QtWidgets.QPushButton(self.centralwidget)
        self.mt.setMinimumSize(QtCore.QSize(52, 52))
        self.mt.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.mt.setFont(font)
        self.mt.setObjectName("mt")
        self.gridLayout.addWidget(self.mt, 6, 8, 1, 1)
        self.indium = QtWidgets.QPushButton(self.centralwidget)
        self.indium.setMinimumSize(QtCore.QSize(52, 52))
        self.indium.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.indium.setFont(font)
        self.indium.setObjectName("indium")
        self.gridLayout.addWidget(self.indium, 4, 12, 1, 1)
        self.hs = QtWidgets.QPushButton(self.centralwidget)
        self.hs.setMinimumSize(QtCore.QSize(52, 52))
        self.hs.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hs.setFont(font)
        self.hs.setObjectName("hs")
        self.gridLayout.addWidget(self.hs, 6, 7, 1, 1)
        self.bh = QtWidgets.QPushButton(self.centralwidget)
        self.bh.setMinimumSize(QtCore.QSize(52, 52))
        self.bh.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bh.setFont(font)
        self.bh.setObjectName("bh")
        self.gridLayout.addWidget(self.bh, 6, 6, 1, 1)
        self.te = QtWidgets.QPushButton(self.centralwidget)
        self.te.setMinimumSize(QtCore.QSize(52, 52))
        self.te.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.te.setFont(font)
        self.te.setObjectName("te")
        self.gridLayout.addWidget(self.te, 4, 15, 1, 1)
        self.sg = QtWidgets.QPushButton(self.centralwidget)
        self.sg.setMinimumSize(QtCore.QSize(52, 52))
        self.sg.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sg.setFont(font)
        self.sg.setObjectName("sg")
        self.gridLayout.addWidget(self.sg, 6, 5, 1, 1)
        self.db = QtWidgets.QPushButton(self.centralwidget)
        self.db.setMinimumSize(QtCore.QSize(52, 52))
        self.db.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.db.setFont(font)
        self.db.setObjectName("db")
        self.gridLayout.addWidget(self.db, 6, 4, 1, 1)
        self.mo = QtWidgets.QPushButton(self.centralwidget)
        self.mo.setMinimumSize(QtCore.QSize(52, 52))
        self.mo.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.mo.setFont(font)
        self.mo.setObjectName("mo")
        self.gridLayout.addWidget(self.mo, 4, 5, 1, 1)
        self.rf = QtWidgets.QPushButton(self.centralwidget)
        self.rf.setMinimumSize(QtCore.QSize(52, 52))
        self.rf.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rf.setFont(font)
        self.rf.setObjectName("rf")
        self.gridLayout.addWidget(self.rf, 6, 3, 1, 1)
        self.lr = QtWidgets.QPushButton(self.centralwidget)
        self.lr.setMinimumSize(QtCore.QSize(52, 52))
        self.lr.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lr.setFont(font)
        self.lr.setObjectName("lr")
        self.gridLayout.addWidget(self.lr, 6, 2, 1, 1)
        self.xe = QtWidgets.QPushButton(self.centralwidget)
        self.xe.setMinimumSize(QtCore.QSize(52, 52))
        self.xe.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.xe.setFont(font)
        self.xe.setObjectName("xe")
        self.gridLayout.addWidget(self.xe, 4, 17, 1, 1)
        self.ra = QtWidgets.QPushButton(self.centralwidget)
        self.ra.setMinimumSize(QtCore.QSize(52, 52))
        self.ra.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ra.setFont(font)
        self.ra.setObjectName("ra")
        self.gridLayout.addWidget(self.ra, 6, 1, 1, 1)
        self.fr = QtWidgets.QPushButton(self.centralwidget)
        self.fr.setMinimumSize(QtCore.QSize(52, 52))
        self.fr.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.fr.setFont(font)
        self.fr.setObjectName("fr")
        self.gridLayout.addWidget(self.fr, 6, 0, 1, 1)
        self.rn = QtWidgets.QPushButton(self.centralwidget)
        self.rn.setMinimumSize(QtCore.QSize(52, 52))
        self.rn.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rn.setFont(font)
        self.rn.setObjectName("rn")
        self.gridLayout.addWidget(self.rn, 5, 17, 1, 1)
        self.at = QtWidgets.QPushButton(self.centralwidget)
        self.at.setMinimumSize(QtCore.QSize(52, 52))
        self.at.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.at.setFont(font)
        self.at.setObjectName("at")
        self.gridLayout.addWidget(self.at, 5, 16, 1, 1)
        self.sb = QtWidgets.QPushButton(self.centralwidget)
        self.sb.setMinimumSize(QtCore.QSize(52, 52))
        self.sb.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb.setFont(font)
        self.sb.setObjectName("sb")
        self.gridLayout.addWidget(self.sb, 4, 14, 1, 1)
        self.po = QtWidgets.QPushButton(self.centralwidget)
        self.po.setMinimumSize(QtCore.QSize(52, 52))
        self.po.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.po.setFont(font)
        self.po.setObjectName("po")
        self.gridLayout.addWidget(self.po, 5, 15, 1, 1)
        self.bi = QtWidgets.QPushButton(self.centralwidget)
        self.bi.setMinimumSize(QtCore.QSize(52, 52))
        self.bi.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.bi.setFont(font)
        self.bi.setObjectName("bi")
        self.gridLayout.addWidget(self.bi, 5, 14, 1, 1)
        self.pd = QtWidgets.QPushButton(self.centralwidget)
        self.pd.setMinimumSize(QtCore.QSize(52, 52))
        self.pd.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pd.setFont(font)
        self.pd.setObjectName("pd")
        self.gridLayout.addWidget(self.pd, 4, 9, 1, 1)
        self.pb = QtWidgets.QPushButton(self.centralwidget)
        self.pb.setMinimumSize(QtCore.QSize(52, 52))
        self.pb.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb.setFont(font)
        self.pb.setObjectName("pb")
        self.gridLayout.addWidget(self.pb, 5, 13, 1, 1)
        self.tl = QtWidgets.QPushButton(self.centralwidget)
        self.tl.setMinimumSize(QtCore.QSize(52, 52))
        self.tl.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tl.setFont(font)
        self.tl.setObjectName("tl")
        self.gridLayout.addWidget(self.tl, 5, 12, 1, 1)
        self.hg = QtWidgets.QPushButton(self.centralwidget)
        self.hg.setMinimumSize(QtCore.QSize(52, 52))
        self.hg.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hg.setFont(font)
        self.hg.setObjectName("hg")
        self.gridLayout.addWidget(self.hg, 5, 11, 1, 1)
        self.tc = QtWidgets.QPushButton(self.centralwidget)
        self.tc.setMinimumSize(QtCore.QSize(52, 52))
        self.tc.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tc.setFont(font)
        self.tc.setObjectName("tc")
        self.gridLayout.addWidget(self.tc, 4, 6, 1, 1)
        self.au = QtWidgets.QPushButton(self.centralwidget)
        self.au.setMinimumSize(QtCore.QSize(52, 52))
        self.au.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.au.setFont(font)
        self.au.setObjectName("au")
        self.gridLayout.addWidget(self.au, 5, 10, 1, 1)
        self.pt = QtWidgets.QPushButton(self.centralwidget)
        self.pt.setMinimumSize(QtCore.QSize(52, 52))
        self.pt.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pt.setFont(font)
        self.pt.setObjectName("pt")
        self.gridLayout.addWidget(self.pt, 5, 9, 1, 1)
        self.y = QtWidgets.QPushButton(self.centralwidget)
        self.y.setMinimumSize(QtCore.QSize(52, 52))
        self.y.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.y.setFont(font)
        self.y.setObjectName("y")
        self.gridLayout.addWidget(self.y, 4, 2, 1, 1)
        self.ir = QtWidgets.QPushButton(self.centralwidget)
        self.ir.setMinimumSize(QtCore.QSize(52, 52))
        self.ir.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ir.setFont(font)
        self.ir.setObjectName("ir")
        self.gridLayout.addWidget(self.ir, 5, 8, 1, 1)
        self.os = QtWidgets.QPushButton(self.centralwidget)
        self.os.setMinimumSize(QtCore.QSize(52, 52))
        self.os.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.os.setFont(font)
        self.os.setObjectName("os")
        self.gridLayout.addWidget(self.os, 5, 7, 1, 1)
        self.sn = QtWidgets.QPushButton(self.centralwidget)
        self.sn.setMinimumSize(QtCore.QSize(52, 52))
        self.sn.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sn.setFont(font)
        self.sn.setObjectName("sn")
        self.gridLayout.addWidget(self.sn, 4, 13, 1, 1)
        self.re = QtWidgets.QPushButton(self.centralwidget)
        self.re.setMinimumSize(QtCore.QSize(52, 52))
        self.re.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.re.setFont(font)
        self.re.setObjectName("re")
        self.gridLayout.addWidget(self.re, 5, 6, 1, 1)
        self.w = QtWidgets.QPushButton(self.centralwidget)
        self.w.setMinimumSize(QtCore.QSize(52, 52))
        self.w.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.w.setFont(font)
        self.w.setObjectName("w")
        self.gridLayout.addWidget(self.w, 5, 5, 1, 1)
        self.rh = QtWidgets.QPushButton(self.centralwidget)
        self.rh.setMinimumSize(QtCore.QSize(52, 52))
        self.rh.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.rh.setFont(font)
        self.rh.setObjectName("rh")
        self.gridLayout.addWidget(self.rh, 4, 8, 1, 1)
        self.ta = QtWidgets.QPushButton(self.centralwidget)
        self.ta.setMinimumSize(QtCore.QSize(52, 52))
        self.ta.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ta.setFont(font)
        self.ta.setObjectName("ta")
        self.gridLayout.addWidget(self.ta, 5, 4, 1, 1)
        self.n = QtWidgets.QPushButton(self.centralwidget)
        self.n.setMinimumSize(QtCore.QSize(52, 52))
        self.n.setMaximumSize(QtCore.QSize(52, 52))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.n.setFont(font)
        self.n.setObjectName("n")
        self.gridLayout.addWidget(self.n, 1, 14, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.chemical_formula = QtWidgets.QLineEdit(self.centralwidget)
        self.chemical_formula.setPlaceholderText("")
        self.chemical_formula.setObjectName("chemical_formula")
        self.horizontalLayout.addWidget(self.chemical_formula)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_3.addWidget(self.pushButton_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1160, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.h.clicked.connect(MainWindow.h_button)
        self.he.clicked.connect(MainWindow.he_button)
        self.li.clicked.connect(MainWindow.li_button)
        self.be.clicked.connect(MainWindow.be_button)
        self.b.clicked.connect(MainWindow.b_button)
        self.c.clicked.connect(MainWindow.c_button)
        self.n.clicked.connect(MainWindow.n_button)
        self.o.clicked.connect(MainWindow.o_button)
        self.f.clicked.connect(MainWindow.f_button)
        self.ne.clicked.connect(MainWindow.ne_button)
        self.na.clicked.connect(MainWindow.na_button)
        self.mg.clicked.connect(MainWindow.mg_button)
        self.al.clicked.connect(MainWindow.al_button)
        self.si.clicked.connect(MainWindow.si_button)
        self.p.clicked.connect(MainWindow.p_button)
        self.s.clicked.connect(MainWindow.s_button)
        self.cl.clicked.connect(MainWindow.cl_button)
        self.ar.clicked.connect(MainWindow.ar_button)
        self.k.clicked.connect(MainWindow.k_button)
        self.ca.clicked.connect(MainWindow.ca_button)
        self.sc.clicked.connect(MainWindow.sc_button)
        self.ti.clicked.connect(MainWindow.ti_button)
        self.v.clicked.connect(MainWindow.v_button)
        self.cr.clicked.connect(MainWindow.cr_button)
        self.mn.clicked.connect(MainWindow.mn_button)
        self.fe.clicked.connect(MainWindow.fe_button)
        self.co.clicked.connect(MainWindow.co_button)
        self.ni.clicked.connect(MainWindow.ni_button)
        self.cu.clicked.connect(MainWindow.cu_button)
        self.zn.clicked.connect(MainWindow.zn_button)
        self.ga.clicked.connect(MainWindow.ga_button)
        self.ge.clicked.connect(MainWindow.ge_button)
        self.arsenic.clicked.connect(MainWindow.as_button)
        self.se.clicked.connect(MainWindow.se_button)
        self.br.clicked.connect(MainWindow.br_button)
        self.kr.clicked.connect(MainWindow.kr_button)
        self.rb.clicked.connect(MainWindow.rb_button)
        self.sr.clicked.connect(MainWindow.sr_button)
        self.y.clicked.connect(MainWindow.y_button)
        self.zr.clicked.connect(MainWindow.zr_button)
        self.nb.clicked.connect(MainWindow.nb_button)
        self.mo.clicked.connect(MainWindow.mo_button)
        self.tc.clicked.connect(MainWindow.tc_button)
        self.ru.clicked.connect(MainWindow.ru_button)
        self.rh.clicked.connect(MainWindow.rh_button)
        self.pd.clicked.connect(MainWindow.pd_button)
        self.ag.clicked.connect(MainWindow.ag_button)
        self.cd.clicked.connect(MainWindow.cd_button)
        self.indium.clicked.connect(MainWindow.in_button)
        self.sn.clicked.connect(MainWindow.sn_button)
        self.sb.clicked.connect(MainWindow.sb_button)
        self.te.clicked.connect(MainWindow.te_button)
        self.i.clicked.connect(MainWindow.i_button)
        self.xe.clicked.connect(MainWindow.xe_button)
        self.cs.clicked.connect(MainWindow.cs_button)
        self.ba.clicked.connect(MainWindow.ba_button)
        self.lu.clicked.connect(MainWindow.lu_button)
        self.hf.clicked.connect(MainWindow.hf_button)
        self.ta.clicked.connect(MainWindow.ta_button)
        self.w.clicked.connect(MainWindow.w_button)
        self.re.clicked.connect(MainWindow.re_button)
        self.os.clicked.connect(MainWindow.os_button)
        self.ir.clicked.connect(MainWindow.ir_button)
        self.pt.clicked.connect(MainWindow.pt_button)
        self.au.clicked.connect(MainWindow.au_button)
        self.hg.clicked.connect(MainWindow.hg_button)
        self.tl.clicked.connect(MainWindow.tl_button)
        self.pb.clicked.connect(MainWindow.pb_button)
        self.bi.clicked.connect(MainWindow.bi_button)
        self.po.clicked.connect(MainWindow.po_button)
        self.at.clicked.connect(MainWindow.at_button)
        self.rn.clicked.connect(MainWindow.rn_button)
        self.fr.clicked.connect(MainWindow.fr_button)
        self.ra.clicked.connect(MainWindow.ra_button)
        self.lr.clicked.connect(MainWindow.lr_button)
        self.rf.clicked.connect(MainWindow.rf_button)
        self.db.clicked.connect(MainWindow.db_button)
        self.sg.clicked.connect(MainWindow.sg_button)
        self.bh.clicked.connect(MainWindow.bh_button)
        self.hs.clicked.connect(MainWindow.hs_button)
        self.mt.clicked.connect(MainWindow.mt_button)
        self.ds.clicked.connect(MainWindow.ds_button)
        self.rg.clicked.connect(MainWindow.rg_button)
        self.cn.clicked.connect(MainWindow.cn_button)
        self.nh.clicked.connect(MainWindow.nh_button)
        self.fl.clicked.connect(MainWindow.fl_button)
        self.mc.clicked.connect(MainWindow.mc_button)
        self.lv.clicked.connect(MainWindow.lv_button)
        self.ts.clicked.connect(MainWindow.ts_button)
        self.og.clicked.connect(MainWindow.og_button)
        self.pushButton_3.clicked.connect(MainWindow.cancel)
        self.pushButton_2.clicked.connect(MainWindow.ok)
        self.pushButton.clicked.connect(MainWindow.reset_text_field)
        self.chemical_formula.textChanged['QString'].connect(MainWindow.chemical_formula_changed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ba.setText(_translate("MainWindow", "Ba"))
        self.ti.setText(_translate("MainWindow", "Ti"))
        self.si.setText(_translate("MainWindow", "Si"))
        self.k.setText(_translate("MainWindow", "K"))
        self.p.setText(_translate("MainWindow", "P"))
        self.b.setText(_translate("MainWindow", "B"))
        self.cl.setText(_translate("MainWindow", "Cl"))
        self.al.setText(_translate("MainWindow", "Al"))
        self.sc.setText(_translate("MainWindow", "Sc"))
        self.ne.setText(_translate("MainWindow", "Ne"))
        self.ca.setText(_translate("MainWindow", "Ca"))
        self.ni.setText(_translate("MainWindow", "Ni"))
        self.s.setText(_translate("MainWindow", "S"))
        self.mg.setText(_translate("MainWindow", "Mg"))
        self.i.setText(_translate("MainWindow", "I"))
        self.be.setText(_translate("MainWindow", "Be"))
        self.kr.setText(_translate("MainWindow", "Kr"))
        self.fe.setText(_translate("MainWindow", "Fe"))
        self.br.setText(_translate("MainWindow", "Br"))
        self.h.setText(_translate("MainWindow", "H"))
        self.co.setText(_translate("MainWindow", "Co"))
        self.ge.setText(_translate("MainWindow", "Ge"))
        self.zn.setText(_translate("MainWindow", "Zn"))
        self.v.setText(_translate("MainWindow", "V"))
        self.na.setText(_translate("MainWindow", "Na"))
        self.cr.setText(_translate("MainWindow", "Cr"))
        self.mn.setText(_translate("MainWindow", "Mn"))
        self.ar.setText(_translate("MainWindow", "Ar"))
        self.ga.setText(_translate("MainWindow", "Ga"))
        self.li.setText(_translate("MainWindow", "Li"))
        self.he.setText(_translate("MainWindow", "He"))
        self.cu.setText(_translate("MainWindow", "Cu"))
        self.c.setText(_translate("MainWindow", "C"))
        self.o.setText(_translate("MainWindow", "O"))
        self.f.setText(_translate("MainWindow", "F"))
        self.hf.setText(_translate("MainWindow", "Hf"))
        self.lu.setText(_translate("MainWindow", "Lu"))
        self.nb.setText(_translate("MainWindow", "Nb"))
        self.se.setText(_translate("MainWindow", "Se"))
        self.arsenic.setText(_translate("MainWindow", "As"))
        self.ag.setText(_translate("MainWindow", "Ag"))
        self.sr.setText(_translate("MainWindow", "Sr"))
        self.zr.setText(_translate("MainWindow", "Zr"))
        self.rb.setText(_translate("MainWindow", "Rb"))
        self.og.setText(_translate("MainWindow", "Og"))
        self.ts.setText(_translate("MainWindow", "Ts"))
        self.lv.setText(_translate("MainWindow", "Lv"))
        self.mc.setText(_translate("MainWindow", "Mc"))
        self.cd.setText(_translate("MainWindow", "Cd"))
        self.fl.setText(_translate("MainWindow", "Fl"))
        self.nh.setText(_translate("MainWindow", "Nh"))
        self.cs.setText(_translate("MainWindow", "Cs"))
        self.cn.setText(_translate("MainWindow", "Cn"))
        self.rg.setText(_translate("MainWindow", "Rg"))
        self.ru.setText(_translate("MainWindow", "Ru"))
        self.ds.setText(_translate("MainWindow", "Ds"))
        self.mt.setText(_translate("MainWindow", "Mt"))
        self.indium.setText(_translate("MainWindow", "In"))
        self.hs.setText(_translate("MainWindow", "Hs"))
        self.bh.setText(_translate("MainWindow", "Bh"))
        self.te.setText(_translate("MainWindow", "Te"))
        self.sg.setText(_translate("MainWindow", "Sg"))
        self.db.setText(_translate("MainWindow", "Db"))
        self.mo.setText(_translate("MainWindow", "Mo"))
        self.rf.setText(_translate("MainWindow", "Rf"))
        self.lr.setText(_translate("MainWindow", "Lr"))
        self.xe.setText(_translate("MainWindow", "Xe"))
        self.ra.setText(_translate("MainWindow", "Ra"))
        self.fr.setText(_translate("MainWindow", "Fr"))
        self.rn.setText(_translate("MainWindow", "Rn"))
        self.at.setText(_translate("MainWindow", "At"))
        self.sb.setText(_translate("MainWindow", "Sb"))
        self.po.setText(_translate("MainWindow", "Po"))
        self.bi.setText(_translate("MainWindow", "Bi"))
        self.pd.setText(_translate("MainWindow", "Pd"))
        self.pb.setText(_translate("MainWindow", "Pb"))
        self.tl.setText(_translate("MainWindow", "Tl"))
        self.hg.setText(_translate("MainWindow", "Hg"))
        self.tc.setText(_translate("MainWindow", "Tc"))
        self.au.setText(_translate("MainWindow", "Au"))
        self.pt.setText(_translate("MainWindow", "Pt"))
        self.y.setText(_translate("MainWindow", "Y"))
        self.ir.setText(_translate("MainWindow", "Ir"))
        self.os.setText(_translate("MainWindow", "Os"))
        self.sn.setText(_translate("MainWindow", "Sn"))
        self.re.setText(_translate("MainWindow", "Re"))
        self.w.setText(_translate("MainWindow", "W"))
        self.rh.setText(_translate("MainWindow", "Rh"))
        self.ta.setText(_translate("MainWindow", "Ta"))
        self.n.setText(_translate("MainWindow", "N"))
        self.label.setText(_translate("MainWindow", "Chemical Formula: "))
        self.pushButton.setText(_translate("MainWindow", "X"))
        self.pushButton_3.setText(_translate("MainWindow", "Cancel"))
        self.pushButton_2.setText(_translate("MainWindow", "OK"))

